version: "3"
services:
  client:
    container_name: "client"
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - webapp
  api:
    container_name: "api"
    build: ./api
    ports:
      - "3001:3001"
    networks:
      - webapp
networks:
  webapp: